### PR TITLE
fix: keep an index to latest block in the database

### LINKED ISSUE #2187: Ganache-cli does not restore blockchain correctly after killing the process or reboot
Version:  **ganache v7.0.0-alpha.2 (@ganache/cli: 0.1.1-alpha.2, @ganache/core: 0.1.1-alpha.2)**
Operating System: **Ubuntu 20.04.3 LTS**

I've noticed an issue with Ganache-cli, when i save the database in a directory using --database.dbPath and reboot my system or kill the process and then restart ganache using the same database it seems to go back in time and doesn't reload the exact state of the blockchain when the process was killed or reboot occurred.

I know rebooting or killing the process isn't an ideal way to stop ganache, but i am testing worst case scenario of using this in a production envrionment, so its important to retain the exact blockchain state.

**Proof of Concept:**
**Start ganache:**
`ganache-cli --database.dbPath /opt/db  -a 20 --wallet.defaultBalance 10 --wallet.mnemonic "* * * * * * * * * * * * -g 0 -p 7545 --chain.networkId 111 -h 127.0.0.1 --miner.blockTime 0 --server.ws --chain.hardfork berlin 
`
**Check the balance of an account with Ether:**
0x***** : 10 Ether

**Send 5 Ether to another account**

**Check Balance**
0x***** : 5 Ether

**Reboot**

**Restart Ganache**
`ganache-cli --database.dbPath /opt/db  -a 20 --wallet.defaultBalance 10 --wallet.mnemonic "* * * * * * * * * * * * -g 0 -p 7545 --chain.networkId 111 -h 127.0.0.1 --miner.blockTime 0 --server.ws --chain.hardfork berlin 
`

**Check Balance**
0x***** : 10 Ether

### PR DESCRIPTION
**Pull request by davidmurdoch**
fixes #2187

### CODE REVIEW

File: src/chains/ethereum/ethereum/src/data-managers/block-manager.ts [hunk 1]
```diff
@@ -261,31 +263,68 @@ export default class BlockManager extends Manager<Block> {
...
-          this.earliest = new Block(data, this.#common);
-        })
-        .on("error", (err: Error) => {
-          reject(err);
-        })
-        .on("end", () => {
-          resolve(void 0);
-        });
+  /**
+   * Updated the "latest" index to point to the given number
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/data-managers/block-manager.ts]:
```suggestion
   * Updates the "latest" index to point to the given number.
```

File: src/chains/ethereum/ethereum/src/data-managers/block-manager.ts [hunk 2]
```diff
@@ -261,31 +263,68 @@ export default class BlockManager extends Manager<Block> {
...
 
-      this.base
-        .createValueStream({ reverse: true, limit: 1 })
-        .on("data", (data: Buffer) => {
-          this.latest = new Block(data, this.#common);
-        })
-        .on("error", (err: Error) => {
-          reject(err);
+  /**
+   * updates the this.latest and this.earliest properties with data
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/data-managers/block-manager.ts]:
```suggestion
   * Updates the this.latest and this.earliest properties with data
```

File: src/chains/ethereum/ethereum/tests/database.test.ts [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+    if (provider) {
+      await provider.disconnect();
+    }
+  });
+
+  it("resumes blockchain from a prior state", async () => {
+    const dir = await readdir(dbPath);
+    assert(dir.length > 0);
+
+    // mine 255 blocks to ensure "latest" can be resumed properly
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/tests/database.test.ts]:
```suggestion
    // mine 256 blocks to ensure "latest" can be resumed properly
```

**Review by MicaiahReid — CHANGES_REQUESTED** [review]
A few small grammar fixes. Cool tests!

**Review by MicaiahReid — APPROVED** [review]
