### PR TITLE
fix: resolve hardfork for blocks by blocknumber and timestamp

### LINKED ISSUE #4450: Error "Cannot mix BigInt and other types" when debugging on a forked chain
Likely related to: #4359.  I thought about posting this just as a comment there in fact, but since they might be separate issues, I'm filing separate issues.  Feel free to combine these if appropriate.

Here's another transaction that causes Ganache to incorrectly error when doing a `debug_traceTransaction` on a forked chain.  However, in this case, the error response is different.  Specifically, it's:

```
{
  id: 1687377797355,
  jsonrpc: '2.0',
  error: {
    message: 'Cannot mix BigInt and other types, use explicit conversions',
    stack: 'TypeError: Cannot mix BigInt and other types, use explicit conversions\n' +
      '    at t.calculateIntrinsicGas (/home/sniffnoy/.nvm/versions/node/v14.21.3/lib/node_modules/ganache/dist/node/1.js:2:203481)\n' +
      '    at EIP1559FeeMarketTransaction.calculateIntrinsicGas (/home/sniffnoy/.nvm/versions/node/v14.21.3/lib/node_modules/ganache/dist/node/1.js:2:204086)\n' +
      '    at EIP1559FeeMarketTransaction.calculateIntrinsicGas (/home/sniffnoy/.nvm/versions/node/v14.21.3/lib/node_modules/ganache/dist/node/1.js:2:206975)\n' +
      '    at Object.getBaseFee (/home/sniffnoy/.nvm/versions/node/v14.21.3/lib/node_modules/ganache/dist/node/1.js:2:206679)\n' +
      '    at VM._runTx (/home/sniffnoy/.nvm/versions/node/v14.21.3/lib/node_modules/ganache/dist/node/0.js:2:3813191)\n' +
      '    at async VM.runTx (/home/sniffnoy/.nvm/versions/node/v14.21.3/lib/node_modules/ganache/dist/node/0.js:2:3821314)\n' +
      '    at async Blockchain.<anonymous> (/home/sniffnoy/.nvm/versions/node/v14.21.3/lib/node_modules/ganache/dist/node/1.js:2:76082)\n' +
      '    at async Blockchain.<anonymous> (/home/sniffnoy/.nvm/versions/node/v14.21.3/lib/node_modules/ganache/dist/node/1.js:2:76291)\n' +
      '    at async Blockchain.traceTransaction (/home/sniffnoy/.nvm/versions/node/v14.21.3/lib/node_modules/ganache/dist/node/1.js:2:85688)',
    code: -32700
  }
}
```

The transaction this occurs with is transaction `0x84f82b79b516aa64f38797f204e09a49e821f7f9353723545dfd600e99b60955` on Sepolia, which I forked with `ganache -f sepolia`.

As with #4359, this error occurs both in Ganache 7.8.0 and Ganache 7.7.0, but not Ganache 7.6.0.

### PR DESCRIPTION
**Pull request by jeffsmale90**
Starting with Shanghai, hardforks are determined by timestamp, rather than block number. When resolving the hardfork to use for a given block, we now consider the blocknumber and the timestamp.

fixes: #4450 (in that the correct hardfork is now resolved, which is not `mergeForkIdTransition`)

See #4463

### CODE REVIEW

File: src/chains/ethereum/ethereum/src/forking/fork.ts [hunk 1]
```diff
@@ -295,13 +290,16 @@ export class Fork {
         let hardfork;
         // hardforks are iterated from earliest to latest
         for (const hf of common.hardforks()) {
-          if (hf.block === null) continue;
-          if (blockNumber >= BigInt(hf.block)) {
+          if (hf.timestamp) {
+            const hfTimestamp = BigInt(hf.timestamp);
+            if (block.timestamp >= hfTimestamp) {
+              hardfork = hf.name;
+            }
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/src/forking/fork.ts:317]: Can we do `else { break; }` here? Since we rely on the `hardforks()` list to be in the order already?

File: src/chains/ethereum/ethereum/src/forking/fork.ts [hunk 2]
```diff
@@ -275,18 +277,11 @@ export class Fork {
...
-  /**
-   * If the `blockNumber` is before our `fork.blockNumber`, return a `Common`
-   * instance, applying the rules from the remote chain's `common` via its
-   * original `chainId`. If the remote chain's `chainId` is now "known", return
-   * a `Common` with our local `common`'s rules applied, but with the remote
-   * chain's `chainId`. If the block is greater than or equal to our
-   * `fork.blockNumber` return `common`.
-   * @param common -
-   * @param blockNumber -
-   */
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/src/forking/fork.ts:287]: I think this comment was useful. Can we update it (maybe add in something about the timestamp stuff)

**Review by davidmurdoch — CHANGES_REQUESTED** [review]

File: src/chains/ethereum/ethereum/src/forking/fork.ts (hunk 2 above)
Comment (jeffsmale90) [reply src/chains/ethereum/ethereum/src/forking/fork.ts:287]: agreed - it's a little unweildy, happy to reworder it further if you don't like it.

File: src/chains/ethereum/ethereum/src/forking/fork.ts (hunk 1 above)
Comment (jeffsmale90) [reply src/chains/ethereum/ethereum/src/forking/fork.ts:317]: yep, likewise in the blocknumber case

**Review by davidmurdoch — APPROVED** [review]
