### PR TITLE
fix: add new `Ethereum` types namespace to fix types

### LINKED ISSUE #2134: Ganache v7.0.0 - typings are broken
```
node_modules/ganache/dist/ganache.d.ts:16:39 - error TS2307: Cannot find module 'ipfs-core/src/components' or its corresponding type declarations.

16 import { ipfsCoreSrcComponents } from 'ipfs-core/src/components';
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/ganache/dist/ganache.d.ts:18:24 - error TS2307: Cannot find module '@filecoin-shipyard/lotus-client-schema' or its corresponding type declarations.

18 import { Schema } from '@filecoin-shipyard/lotus-client-schema';
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/ganache/dist/ganache.d.ts:19:24 - error TS2307: Cannot find module 'seedrandom' or its corresponding type declarations.

19 import seedrandom from 'seedrandom';
                          ~~~~~~~~~~~~

node_modules/ganache/dist/ganache.d.ts:3704:75 - error TS2307: Cannot find module './types/subscriptions' or its corresponding type declarations.

3704     get provider(): FilecoinProvider_2<JsonRpcRequest<FilecoinApi, import("./types/subscriptions").SubscriptionMethod.ChannelClosed | "initialize" | "stop" | "Filecoin.Version" | "Filecoin.ID" | "Filecoin.ChainGetGenesis" | "Filecoin.ChainHead" | "Filecoin.ChainNotify" | "Filecoin.ChainGetTipSet" | "Filecoin.ChainGetTipSetByHeight" | "Filecoin.ChainGetBlock" | "Filecoin.ChainGetBlockMessages" | "Filecoin.ChainGetMessage" | "Filecoin.MpoolGetNonce" | "Filecoin.MpoolPush" | "Filecoin.MpoolBatchPush" | "Filecoin.MpoolPushMessage" | "Filecoin.MpoolBatchPushMessage" | "Filecoin.MpoolClear" | "Filecoin.MpoolPending" | "Filecoin.MpoolSelect" | "Filecoin.ActorAddress" | "Filecoin.StateListMiners" | "Filecoin.StateMinerPower" | "Filecoin.StateMinerInfo" | "Filecoin.WalletDefaultAddress" | "Filecoin.WalletSetDefault" | "Filecoin.WalletBalance" | "Filecoin.WalletNew" | "Filecoin.WalletList" | "Filecoin.WalletHas" | "Filecoin.WalletDelete" | "Filecoin.WalletExport" | "Filecoin.WalletImport" | "Filecoin.WalletSign" | "Filecoin.WalletSignMessage" | "Filecoin.WalletVerify" | "Filecoin.WalletValidateAddress" | "Filecoin.ClientStartDeal" | "Filecoin.ClientListDeals" | "Filecoin.ClientGetDealInfo" | "Filecoin.ClientGetDealStatus" | "Filecoin.ClientGetDealUpdates" | "Filecoin.ClientFindData" | "Filecoin.ClientHasLocal" | "Filecoin.ClientRetrieve" | "Ganache.MineTipset" | "Ganache.EnableMiner" | "Ganache.DisableMiner" | "Ganache.MinerEnabled" | "Ganache.MinerEnabledNotify" | "Ganache.GetDealById">>;
                                                                               ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/ganache/dist/ganache.d.ts:7101:163 - error TS2344: Type 'ExclusiveGroup<C, K>' does not satisfy the constraint 'unknown[]'.
  Type 'ExclusiveGroups<C>[ExclusiveGroupIndex<C>]' is not assignable to type 'unknown[]'.
    Type 'ExclusiveGroups<C>[number]' is not assignable to type 'unknown[]'.

7101 declare type ExclusiveGroupOptionName<C extends Base.Config, K extends ExclusiveGroupIndex<C> = ExclusiveGroupIndex<C>> = Extract<OptionName<C>, DeepTupleToUnion<ExclusiveGroup<C, K>>>;
                                                                                                                                                                       ~~~~~~~~~~~~~~~~~~~~

node_modules/ganache/dist/ganache.d.ts:7113:141 - error TS2344: Type 'G' does not satisfy the constraint 'unknown[]'.
  Type 'ExclusiveGroup<C, ExclusiveGroupIndex<C>>' is not assignable to type 'unknown[]'.
    Type 'ExclusiveGroups<C>[number]' is not assignable to type 'unknown[]'.

7113 declare type ExclusiveGroupOptionsByGroup<C extends Base.Config, G extends ExclusiveGroup<C>> = PairsToMapping<ExclusiveGroupOptionPairs<C, G>>;
                                                                                                                                                 ~

node_modules/ganache/dist/ganache.d.ts:10699:5 - error TS2416: Property 'hash' in type 'RuntimeTransaction' is not assignable to the same property in base type 'BaseTransaction'.
  Type 'Data | null' is not assignable to type 'Data'.
    Type 'null' is not assignable to type 'Data'.

10699     hash: Data | null;
          ~~~~


Found 7 errors.
```

Installing the missing dependencies or changing the typeroots doesn't help

### PR DESCRIPTION
**Pull request by davidmurdoch**
We fixed our Ethereum RPC types and put them in a new namespace: `Ethereum`! Use it as follows:

```typescript
import Ganache, {ProviderOptions, Ethereum} from "ganache";

async function getLatestBlock(): Promise<Ethereum.Block> {
  return await provider.request({method: "eth_getBlockByNumber", params: ["latest"]});
}
async function getAccounts(): Promise<string[]> {
  return await provider.request({method: "eth_accounts", params: []});
}
async function sendTransaction(transaction: Ethereum.Transaction): Promise<string> {
  return await provider.request({method: "eth_sendTransaction", params: [transaction]});
}

const options: ProviderOptions = {
  fork: { network: "mainnet" }
};
const provider = Ganache.provider(options);
const accounts  = await getAccounts();
const block = await getLatestBlock();
console.log(block.number); // string
const transaction: Ethereum.Transaction = { from: accounts[0], to: accounts[2], value: "0xffff" };
const hash = await sendTransaction(transaction);
console.log(hash); // string
```

If you find issues or can think of ways we can further improve our types please open a [New Issue](https://github.com/trufflesuite/ganache/issues/new?labels=typescript) (you can view all existing type issues by [filtering our issues by the typescript label](https://github.com/trufflesuite/ganache/issues?q=is%3Aopen+is%3Aissue+label%3Atypescript)).

fixes #2134

### CODE REVIEW

File: scripts/build-docs/index.ts [hunk 1]
```diff
@@ -276,13 +273,14 @@ function getTypeAsString(type: Type): string {
...
-        type.elements ? type.elements.map(getTypeAsString).join(", ") : ""
-      }]`;
+      return `[${type.elements ? type.elements.map(getTypeAsString).join(", ") : ""
+        }]`;
     case "literal":
       // outputs a string literal like `He said, "hello, world"!` as
       // the string `"He said, \"hello, world\"!"`
       return `"${type.value.replace(/"/g, '\\"')}"`;
+    case "intersection":
+      return type.types.map(getTypeAsString).join(" & ");
```
Comment (davidmurdoch) [inline scripts/build-docs/index.ts:296]: This is the only real change in this file. The rest are formatting.

File: src/chains/ethereum/block/src/block.ts [hunk 2]
```diff
@@ -92,19 +97,25 @@ export class Block {
       // leave it out of extra and update the effectiveGasPrice after like this
       tx.updateEffectiveGasPrice(header.baseFeePerGas);
       return txFn(tx);
-    });
+    }) as IncludeTransactions extends true
+      ? (
+          | LegacyTransactionJSON
```
Comment (MicaiahReid) [inline src/chains/ethereum/block/src/block.ts]: Can this be replaced with `TypedTransactionJSON`, which is also exported from `@ganache/ethereum-transaction`?

File: src/chains/ethereum/ethereum/src/api-types.ts [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+  export type SubscriptionOptions = UtilTypes.BaseFilterArgs;
+  export type LogsFilter = UtilTypes.FilterArgs;
+  export type Filter = UtilTypes.RangeFilterArgs;
+  export type SubscriptionName = UtilTypes.SubscriptionName;
+  export type SubscriptionId = UtilTypes.SubscriptionId;
+
+  // transactions
+  export type Transaction = TransactionTypes.Transaction;
+  export type CallTransaction = TransactionTypes.CallTransaction;
+  export type SignedTransaction<
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/api-types.ts]: I'm having second thoughts about this name, `SignedTransaction`. That name made me think it was equivalent to a raw transaction, like what `eth_signTransaction` returns. :/

File: src/chains/ethereum/ethereum/src/api-types.ts [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+
+  // Transaction Pool
+  export type TransactionPoolContent<
+    T extends "external" | "internal" = "external"
+  > = {
+    pending: Record<string, Record<string, PooledTransaction<T>>>;
+    queued: Record<string, Record<string, PooledTransaction<T>>>;
+  };
+
+  // Mine
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/api-types.ts]:
```suggestion
  // evm_mine
```
Would be helpful for me :nerd_face:

File: src/chains/ethereum/ethereum/src/api.ts [hunk 5]
```diff
@@ -53,15 +47,17 @@ import { decode } from "@ganache/rlp";
 import { Address } from "@ganache/ethereum-address";
 import { GanacheRawBlock } from "@ganache/ethereum-block";
 import { Capacity } from "./miner/miner";
+import { Ethereum } from "./api-types";
+import { TypeOutputReturnType } from "ethereumjs-util";
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/api.ts]:
```suggestion
```
Remove unused.

File: src/chains/ethereum/ethereum/src/api.ts [hunk 6]
```diff
@@ -1715,7 +1728,13 @@ export default class EthereumApi implements Api {
    * ```
    */
   @assertArgLength(1)
-  async eth_getTransactionByHash(transactionHash: DATA) {
+  async eth_getTransactionByHash(
+    transactionHash: DATA
+  ): Promise<
+    | Ethereum.SignedTransaction<"internal">
+    | Ethereum.PooledTransaction<"internal">
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/api.ts]: I find it interesting that we return `"internal"` types from RPC methods. Is that name wrong if we're having to externalized them to users?

File: src/chains/ethereum/ethereum/src/provider.ts [hunk 7]
```diff
@@ -91,14 +91,14 @@ function hookEventSystem(
 }
 
 type Primitives = string | number | null | undefined | symbol | bigint;
-type Clean<X> = X extends Primitives
+export type Externalize<X> = X extends Primitives
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/provider.ts]: Some comments explaining these types while they're fresh would be great :sweat_smile:

File: src/packages/cli/src/cli.ts [hunk 8]
```diff
@@ -81,6 +81,10 @@ const closeHandler = async () => {
         console.log("Server has been shut down");
         break;
     }
+    console.log("HEYO");
```
Comment (MicaiahReid) [inline src/packages/cli/src/cli.ts]:
```suggestion
```

File: src/packages/ganache/tests/types.test.ts [hunk 9]
```diff
@@ -0,0 +1,130 @@
...
+  it("return the type for db_putHex", () => {
+    expectMethod<"db_putHex", boolean, 1>();
+  });
+
+  it("returns the type for eth_sendTransaction", () => {
+    expectMethod<"eth_sendTransaction", string, 1>();
+  });
+
+  // Monday, more like
+  // Tuesday? More like
```
Comment (MicaiahReid) [inline src/packages/ganache/tests/types.test.ts]:
```suggestion
```
huh?

File: src/packages/ganache/tests/types.test.ts [hunk 10]
```diff
@@ -0,0 +1,130 @@
...
+  });
+
+  it("return the type for db_putHex", () => {
+    expectMethod<"db_putHex", boolean, 1>();
+  });
+
+  it("returns the type for eth_sendTransaction", () => {
+    expectMethod<"eth_sendTransaction", string, 1>();
+  });
+
```
Comment (MicaiahReid) [inline src/packages/ganache/tests/types.test.ts]:
```suggestion
```

**Review by MicaiahReid — CHANGES_REQUESTED** [review]
I won't pretend to understand those types tests, but they sure do look cool!

This was an initial pass through, I still haven't tested any of it.

File: src/packages/cli/src/cli.ts (hunk 8 above)
Comment (davidmurdoch) [reply src/packages/cli/src/cli.ts]: Oh good catch!

File: src/chains/ethereum/ethereum/src/provider.ts (hunk 7 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/provider.ts]: Done

File: src/chains/ethereum/ethereum/src/api.ts (hunk 6 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/api.ts]: We don't return them to users that way; they get `Externalized` later via `Simplify<ReturnType<EthereumApi[Method]>>`.

Comment (MicaiahReid) [reply src/chains/ethereum/ethereum/src/api.ts]: In what cases do we use `"external"`?

File: src/packages/ganache/tests/types.test.ts (hunk 9 above)
Comment (davidmurdoch) [reply src/packages/ganache/tests/types.test.ts]: github copilot things. woops

File: src/packages/ganache/tests/types.test.ts (hunk 10 above)
Comment (MicaiahReid) [reply src/packages/ganache/tests/types.test.ts]: I meant to group this suggestion with the removal of the "Monday, more like" lines, but missed it. This is just to keep there from being two empty lines rather than one

File: src/chains/ethereum/ethereum/src/api.ts (hunk 6 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/api.ts]: The user does by default: `let tx: Ethereum.SignedTransaction;` is actually `Ethereum.SignedTransaction<"external">`.

File: src/chains/ethereum/ethereum/src/api-types.ts [hunk 11]
```diff
@@ -0,0 +1,195 @@
...
+   */
+  export type Transaction =
+    | Ethereum.Transaction.Legacy
+    | Ethereum.Transaction.EIP1559
+    | Ethereum.Transaction.EIP2930;
+  //#endregion transactions
+
+  //#region call/estimate
+  export namespace Call {
+    export type Transaction =
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/api-types.ts]: It seems backwards and a little harder to follow to export the type before the namespace. Can we switch the order? (Just a slightly easier read, not very important)

File: src/chains/ethereum/ethereum/src/api.ts [hunk 12]
```diff
@@ -6,34 +6,29 @@ import {
...
-  TraceTransactionResult
+  RuntimeError
 } from "@ganache/ethereum-utils";
 import { BaseFeeHeader, Block, RuntimeBlock } from "@ganache/ethereum-block";
 import {
-  TypedRpcTransaction,
+  EIP1559FeeMarketTransaction,
+  EIP2930AccessListTransaction,
+  LegacyTransaction,
+  RuntimeTransaction,
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/api.ts]:
```suggestion
```
Remove unused

File: src/chains/ethereum/ethereum/src/api.ts [hunk 13]
```diff
@@ -6,34 +6,29 @@ import {
...
-  Filter,
-  FilterArgs,
+  InternalFilter,
   FilterTypes,
   QUANTITY,
-  RangeFilterArgs,
-  StorageRangeResult,
-  SubscriptionId,
-  SubscriptionName,
   EthereumRawAccount,
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/api.ts]:
```suggestion
  EthereumRawAccount
```

File: src/chains/ethereum/ethereum/src/api.ts [hunk 14]
```diff
@@ -6,34 +6,29 @@ import {
...
-  TransactionTraceOptions,
-  TraceTransactionResult
+  RuntimeError
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/api.ts]:
```suggestion
```
Remove unused

File: src/packages/cli/src/cli.ts [hunk 15]
```diff
@@ -81,6 +81,9 @@ const closeHandler = async () => {
         console.log("Server has been shut down");
         break;
     }
+    // process.removeAllListeners("SIGINT");
+    // process.removeAllListeners("SIGTERM");
+    // process.removeAllListeners("SIGHUP");
```
Comment (MicaiahReid) [inline src/packages/cli/src/cli.ts]:
```suggestion
```
?

File: src/packages/ganache/tests/types.test.ts [hunk 16]
```diff
@@ -0,0 +1,183 @@
...
+ * `TuplifyUnion` splits booleans into [true, false], but we really want to represent that as just `boolean`
+ */
+type NormalizeBoolean<MaybeBoolean> = MaybeBoolean extends
+  | [true, false]
+  | [false, true]
+  ? [boolean]
+  : MaybeBoolean;
+
+/**
+ * Convert a Union into Tuple a union.
```
Comment (MicaiahReid) [inline src/packages/ganache/tests/types.test.ts]:
```suggestion
 * Convert a Union into a Tuple union.
```
Did I get that right?

**Review by MicaiahReid — CHANGES_REQUESTED** [review]
Excited to have this one merged! I've got some tiny clean up requests

File: src/packages/cli/src/cli.ts (hunk 15 above)
Comment (davidmurdoch) [reply src/packages/cli/src/cli.ts]: no idea. fixed!

File: src/packages/ganache/tests/types.test.ts (hunk 16 above)
Comment (davidmurdoch) [reply src/packages/ganache/tests/types.test.ts]: > Convert a Union into a Tuple

was the right answer. haha. fixed!

**Review by MicaiahReid — APPROVED** [review]
!!!
