### PR TITLE
fix(filecoin): resolve remainder TODOs

### LINKED ISSUE #727: Go back and finalize decisions for TODOs
This is a catch-all issue for me to come back to code and address TODOs (by either implementing them or designating them out of scope)

### PR DESCRIPTION
**Pull request by mikeseese**
This PR resolves #727 by resolving any remainder TODOs that aren't being purposely left in the code for later

### CODE REVIEW

File: src/chains/filecoin/filecoin/src/blockchain.ts [hunk 1]
```diff
@@ -611,13 +613,20 @@ export default class Blockchain extends Emittery.Typed<
             continue;
           }
 
-          // TODO: figure out nonce/error logic
```
Comment (mikeseese) [inline src/chains/filecoin/filecoin/src/blockchain.ts:625]: I went through the nonce logic when errors occur in lotus, and the current implementation is valid, so this TODO was removed

File: src/chains/filecoin/filecoin/src/things/address.ts [hunk 2]
```diff
@@ -154,7 +154,7 @@ class Address extends SerializableLiteral<AddressConfig> {
         );
       }
       default: {
-        return false; // TODO: throw?
```
Comment (mikeseese) [inline src/chains/filecoin/filecoin/src/things/address.ts:158]: I don't think throwing here really makes sense for this function, so I removed the TODO

File: src/chains/filecoin/filecoin/src/blockchain.ts [hunk 3]
```diff
@@ -781,9 +790,6 @@ export default class Blockchain extends Emittery.Typed<
 
     const signature = await account.address.signProposal(proposal);
 
-    // TODO: I'm not sure if should pass in a hex string or the Buffer alone.
-    // I *think* it's the string, as that matches my understanding of the Go code.
-    // That said, node that Buffer vs. hex string returns a different CID...
```
Comment (mikeseese) [inline src/chains/filecoin/filecoin/src/blockchain.ts:797]: This was a TODO from @tcoulter's original code. We can keep it if you want it, but I don't plan on changing the implementation here since we're not ensuring cryptographic integrity. Up to yall! I can make an issue if you want to keep it

**Review by davidmurdoch — APPROVED** [review]

**Comment by mikeseese** [comment]
I got approval from @tcoulter on Slack to merge this without his review (I also got @davidmurdoch's approval to merge without Tim's approval).

Tests fail in this PR due to not having fixes from #877 yet, but I'm going to apply fixes for that in a new PR and merge this for now to be done with it
