### PR TITLE
fix: make `debug_storageRangeAt` return all known keys at transaction index

### LINKED ISSUE #3338: `debug_storageRangeAt` fails to find storage when the slot was created earlier in the same block
## Issue

In some cases, when the transaction index is greater than 0 (i.e. you're not looking at the first transaction in a block), `debug_storageRangeAt` will fail to find storage that was there at the start of the transaction.

This doesn't happen in all cases.  If there was storage at that slot at the start of the block, it seems like it works fine; it will correctly report the storage for that index.  If however there was no storage at that slot at the start of the block, but storage was set in transaction 0, then doing `debug_storageRangeAt` with index 1 will fail to find the storage that was set there in transaction 0.

(At least, that's how the problem looks to me.)

## Reproduction steps

I found this using the `solc8-magic-square` project in the `solidity-test-cases` repo, but I'll admit that this would probably be more easily reproduced with a `SimpleStorage` contract.  So, modify as appropriate.  The relevant fact here is that doing `generateMagicSquare(n)` will set storage slot 0 to the number `n`, at least when `n` is small and odd (you might want to use `SimpleStorage` instead if you don't like being restricted to small odd numbers :P ).

I compiled the project.  I ran `ganache -p 7545 -b 5`.  I then did `truffle migrate` to migrate the project, then `truffle console`.  I then did the following:
```
it = await MagicSquare.deployed()
it.generateMagicSquare(1), it.generateMagicSquare(3) //send both txs, hope they end up in same block
block = await web3.eth.getBlock(/* block number I saw in output */)
block //confirm there are exactly two txs in the block
promisify = require("util").promisify
provider = web3.currentProvider
send = promisify(provider.send.bind(provider))
slothash = web3.utils.soliditySha3("0x" + "00".repeat(32))
await send({ jsonrpc: "2.0", method: "debug_storageRangeAt", id: Date.now(), params: [block.hash, 0, it.address, slothash, 1]}) //no storage returned, as expected
await send({ jsonrpc: "2.0", method: "debug_storageRangeAt", id: Date.now(), params: [block.hash, 1, it.address, slothash, 1]}) //no storage returned... uh-oh!
```

No storage was returned for index 1, despite the slot having been set in index 0.  If you do an `eth_getStorageAt` for the block, you'll be able to see that the slot is correctly set to 3 at the end of the block.

I also tested this with three transactions in the block instead of two; the result was that no storage was returned for any of the three indices.

## Non-reproduction steps

I also did the same thing, but with an extra step of doing `it.generateMagicSquare(5)` in a separate block before doing the two transactions above.  In this case, the problem does not occur; the first `debug_storageRangeAt` shows the correct value of 5, and the second `debug_storageRangeAt` shows the correct value of 1.  The problem only seems to occur when there was no storage present at that slot at the beginning of the block.

(Of course, it's possible I have the exact conditions of the bug incorrect, but I thought this was worth pointing out all the same.)

## Environment

Version: This problem probably exists in all released versions of Ganache 7, since it exists on both 7.0.0 and on 7.3.2.

### LINKED ISSUE #3468: event contexts during debug_traceTransaction are shared between transactions

### PR DESCRIPTION
**Pull request by davidmurdoch**
`debug_storageRangeAt` would sometimes fail to find storage that was there at the start of the transaction if the storage slots were written to in the same block as the target transaction. Ganache now waits to read storage slots until after the requisite transactions in the block have been processed.

Fixes #3338, also fixes #3468

### CODE REVIEW

File: src/chains/ethereum/ethereum/src/api.ts [hunk 1]
```diff
@@ -2931,11 +2931,12 @@ export default class EthereumApi implements Api {
    * console.log(transactionTrace);
    * ```
    */
+  @assertArgLength(1, 2)
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/src/api.ts:3138]: I noticed this was missing from both `debug_` methods so I added it. I can move it to another PR if anyone objects to it being in here.

File: src/chains/ethereum/ethereum/src/api.ts [hunk 2]
```diff
@@ -2931,11 +2931,12 @@ export default class EthereumApi implements Api {
...
   async debug_traceTransaction(
     transactionHash: DATA,
-    options?: Ethereum.TraceTransactionOptions
+    options: Ethereum.TraceTransactionOptions = {}
   ): Promise<Ethereum.TraceTransactionResult<"private">> {
-    return this.#blockchain.traceTransaction(transactionHash, options || {});
+    return this.#blockchain.traceTransaction(transactionHash, options);
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/src/api.ts:3143]: Just a drive-by refactor

File: src/chains/ethereum/ethereum/src/api.ts [hunk 3]
```diff
@@ -2981,14 +2982,22 @@ export default class EthereumApi implements Api {
...
     transactionIndex: number,
     contractAddress: DATA,
     startKey: DATA,
     maxResult: number
   ): Promise<Ethereum.StorageRangeAtResult<"private">> {
-    return this.#blockchain.storageRangeAt(
+    const blockchain = this.#blockchain;
+    if (blockchain.fallback) {
+      throw new Error(
+        "debug_storageRangeAt is not supported on a forked network. See https://github.com/trufflesuite/ganache/issues/3488 for details."
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/src/api.ts:3201]: see the linked issue for why this has to be there.

File: src/chains/ethereum/ethereum/src/blockchain.ts [hunk 4]
```diff
@@ -1164,17 +1162,11 @@ export default class Blockchain extends Emittery<BlockchainTypedEvents> {
...
-    newBlock: RuntimeBlock & { transactions: VmTransaction[] },
-    options: TraceTransactionOptions,
-    keys?: Buffer[],
-    contractAddress?: Buffer
-  ): Promise<TraceTransactionResult> => {
-    let currentDepth = -1;
-    const storageStack: TraceStorageMap[] = [];
-
+    block: RuntimeBlock & { transactions: VmTransaction[] }
+  ): Promise<VM & { stateManager: GanacheStateManager }> => {
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/src/blockchain.ts:1212]: `traceTransaction` previously had `debug_storageRangeAt`-specific logic in it, which was just gross and weird. I've refactored our the common code into `fastForwardVM`.

File: src/chains/ethereum/ethereum/src/blockchain.ts [hunk 5]
```diff
@@ -1187,21 +1179,60 @@ export default class Blockchain extends Emittery<BlockchainTypedEvents> {
...
+      const tx = block.transactions[i] as any;
+      const transactionEventContext = {};
+      this.emit("ganache:vm:tx:before", {
+        context: transactionEventContext
+      });
+      await vm.runTx({ tx, block: block as any });
+      this.emit("ganache:vm:tx:after", {
+        context: transactionEventContext
+      });
+    }
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/src/blockchain.ts]: This is pretty much the same as before, but now we don't have weird branching just for `storageRangeAt`

File: src/chains/ethereum/ethereum/src/blockchain.ts [hunk 6]
```diff
@@ -1324,67 +1356,15 @@ export default class Blockchain extends Emittery<BlockchainTypedEvents> {
...
-      await vm.stateManager.revert();
-    }
+    vm.on("step", stepListener);
+    this.emit("ganache:vm:tx:before", {
+      context: transactionEventContext
+    });
+    await vm.runTx({ tx: transaction as any, block: newBlock as any });
+    this.emit("ganache:vm:tx:after", {
+      context: transactionEventContext
+    });
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/src/blockchain.ts]: This part needed to be added here, as it was previously handled inside the weird loop that had the condition specifically for `storageRangeAt`, here:  https://github.com/trufflesuite/ganache/pull/3470/files#diff-eb13881c7bcdaf19f3b7fe3f7c0b32570442528d3511e250621734dbbcb74992L1379

File: src/chains/ethereum/ethereum/src/blockchain.ts [hunk 7]
```diff
@@ -1398,7 +1378,7 @@ export default class Blockchain extends Emittery<BlockchainTypedEvents> {
   #prepareNextBlock = (
     targetBlock: Block,
     parentBlock: Block,
-    transactionHash: Buffer
+    transactionIndex: number
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/src/blockchain.ts:1455]: Instead of checking if we are done by comparing hashes let's just loop up to (and including) the index the transaction is at. No hash comparisons needed!

File: src/chains/ethereum/ethereum/src/blockchain.ts [hunk 8]
```diff
@@ -1540,102 +1508,53 @@ export default class Blockchain extends Emittery<BlockchainTypedEvents> {
...
-
-    // #3 - use the contractAddress storage trie to get relevant hashed keys
-    const getStorageKeys = () => {
-      const storageTrie = trie.copy(false);
-      // An address's stateRoot is stored in the 3rd rlp entry
-      storageTrie.setContext(
-        decode<EthereumRawAccount>(addressData)[2],
+    let storageTrie: Trie;
+    if (txIndex === 0) {
+      // there are no transactions to run, so let's just grab what we need
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/src/blockchain.ts:1593]: an :sparkles: optimization :sparkles:

File: src/chains/ethereum/ethereum/src/data-managers/account-manager.ts [hunk 9]
```diff
@@ -40,22 +40,6 @@ export default class AccountManager {
     return await trieCopy.get(address.toBuffer());
   }
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/src/data-managers/account-manager.ts:42]: `getStorageAt` wasn't used anywhere

File: src/chains/ethereum/ethereum/src/state-manager.ts [hunk 10]
```diff
@@ -1,20 +1,8 @@
 import SM from "@ethereumjs/vm/dist/state/stateManager";
+import { SecureTrie as Trie } from "merkle-patricia-tree";
 
-export class StateManager extends SM {
-  /**
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/src/state-manager.ts:4]: removed some unused "code"

File: src/chains/ethereum/ethereum/src/state-manager.ts [hunk 11]
```diff
@@ -1,20 +1,8 @@
...
-  //     for (const address of touchedArray) {
-  //       const empty = await this.accountIsEmpty(address);
-  //       if (empty) {
-  //         this._cache.del({ buf: address } as any);
-  //       }
-  //     }
-  //   }
-  //   this._touched.clear();
-  // }
+export class GanacheStateManager extends SM {
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/src/state-manager.ts]: This whole class wasn't being used. So I commandeered it for my own nefarious purposes...

...which is just to get at the base class's private method `_getStorageTrie` without typescript complaining about it.

File: src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts [hunk 12]
```diff
@@ -317,146 +279,151 @@ describe("api", () => {
...
         }
       });
 
       it("should throw an error for transaction indexes out of range", async () => {
         const message = `transaction index 3 is out of range for block ${blockHash}`;
+        // txIndex out of range
+        await assert.rejects(debugStorage(blockHash, 3, 2), { message });
+      });
+
+      it("throws with a forked network", async () => {
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts:365]: the only new test!

File: src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts [hunk 13]
```diff
@@ -134,141 +147,108 @@ describe("api", () => {
...
+              "0x0000000000000000000000000000000000000000000000000000000000000001"
+          }
         };
 
         assert.deepStrictEqual(result.storage, storage);
         assert.strictEqual(result.nextKey, null);
       });
 
-      it("should return correct storage given different transaction indexes", async () => {
+      it("should return correct storage given different storage slot changes at different transaction indexes in same block", async () => {
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts:237]: The updated test!

It now sets a value for the very first time in the middle of a block. This is the exact issue this PR is fixing.

File: src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts [hunk 14]
```diff
@@ -2,33 +2,76 @@ import assert from "assert";
 import { EthereumProvider } from "../../../src/provider";
 import getProvider from "../../helpers/getProvider";
 import compile from "../../helpers/compile";
-import path from "path";
+import { join } from "path";
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts:5]: The previous tests had tons of duplication, so I tried cleaning it up a bit. Hopefully its not worse.

There are (hopefully, ha) only three real changes to this file, and I've left a review comment on all three:

1. edited an existing test to test for the right thing
2. added a test to make sure the forking error is tested.
3. changed a static value in a contract, which changed the expected value in the test.

File: src/chains/ethereum/ethereum/tests/contracts/DebugStorage.sol [hunk 15]
```diff
@@ -5,20 +5,27 @@ contract DebugStorage {
...
   string public valueThree;
+  uint public value4;
 
   event ValueSet(uint);
 
   constructor() payable {
     value = 5;
     valueTwo = 1;
-    valueThree = "hello rpdr";
+    valueThree = "hello world";
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/tests/contracts/DebugStorage.sol:15]: rdpr? huh? I just made this make sense.

File: src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts [hunk 16]
```diff
@@ -40,92 +83,62 @@ describe("api", () => {
...
-            }
+          [VALUE1_KEY.hashKey]: {
+            key: VALUE1_KEY.key,
+            value:
+              "0x0000000000000000000000000000000000000000000000000000000000000005"
+          },
+          [VALUE3_KEY.hashKey]: {
+            key: VALUE3_KEY.key,
+            value:
+              "0x68656c6c6f20776f726c64000000000000000000000000000000000000000016"
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts:113]: I updated the contract value from "hello rdpr" to "hello world", and this change reflects that.

File: src/chains/ethereum/utils/src/types/debug-storage.ts [hunk 17]
```diff
@@ -1,18 +1,14 @@
...
+export type StorageRecords = Record<string, StorageRecord>;
 
 export type StorageRangeAtResult = {
   nextKey: Data | null;
   storage: StorageRecords;
 };
 
 export type StorageKeys = Map<string, { key: Buffer; hashedKey: Buffer }>;
-
-export type RangedStorageKeys = { keys: Buffer[]; nextKey: Data };
```
Comment (davidmurdoch) [inline src/chains/ethereum/utils/src/types/debug-storage.ts:18]: After all the refactoring I noticed this wasn't used anymore /shrug

File: src/chains/ethereum/ethereum/tests/contracts/DebugStorage.sol (hunk 15 above)
Comment (tenthirtyone) [reply src/chains/ethereum/ethereum/tests/contracts/DebugStorage.sol:15]: This should be a separate pr 

jk

File: src/chains/ethereum/ethereum/src/blockchain.ts [hunk 18]
```diff
@@ -1187,21 +1179,60 @@ export default class Blockchain extends Emittery<BlockchainTypedEvents> {
...
       : this.common;
 
     const vm = await VM.create({
-      state: trie,
       activatePrecompiles: false,
       common,
       allowUnlimitedContractSize: this.vm.allowUnlimitedContractSize,
       blockchain,
       stateManager: this.fallback
         ? new ForkStateManager({ common, trie: trie as ForkTrie })
```
Comment (tenthirtyone) [inline src/chains/ethereum/ethereum/src/blockchain.ts]: With `debug_storageRangeAt` [throwing](https://github.com/trufflesuite/ganache/pull/3470/files#diff-33bf12664f527a9e8ee226d4340fc6c3255c690db880c187f0a69166dd24e55fR2995) for the mentioned reason, would `ForkStateManager` be reachable? 

`traceTransaction` is the only other place to use `fastForwardVM` but it has an existing TODO for mainnet forking. I'm guessing this is benign for now but something we eventually want on mainnet forking.

File: src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts [hunk 19]
```diff
@@ -2,33 +2,76 @@ import assert from "assert";
...
+  hashKey: "0x405787fa12a823e0f2b7631cc41b3ba8828b3321ca811111fa75cd3aa3bb5ace",
+  key: "0x0000000000000000000000000000000000000000000000000000000000000002"
+};
+const VALUE4_KEY = {
+  hashKey: "0xc2575a0e9e593c00f959f8c92f12db2869c3395a3b0502d05e2516446f71f85b",
+  key: "0x0000000000000000000000000000000000000000000000000000000000000003"
+};
 
 describe("api", () => {
   describe("storageRangeAt", () => {
```
Comment (tenthirtyone) [inline src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts:25]: This was old/stale, I left it in but it may not be relevant - Per our chat, it might be worthwhile it to add a unit test to ensure zeroed out storage is being properly handled. I believe it is working just fine but we may not explicitly test for it

File: src/chains/ethereum/ethereum/src/api.ts (hunk 3 above)
Comment (MicaiahReid) [reply src/chains/ethereum/ethereum/src/api.ts:3201]: What linked issue? The only linked issue I could find was [this one](https://github.com/trufflesuite/ganache/issues/3338), and it didn't mention forking.

File: src/chains/ethereum/ethereum/src/state-manager.ts (hunk 11 above)
Comment (MicaiahReid) [reply src/chains/ethereum/ethereum/src/state-manager.ts]: Should we standardize to using `GanacheStateManager` across the repo? Currently the only uses of `DefaultStateManager` and `StateManager` are in `precompiles.ts`, but my create access list PR adds a few uses.

File: src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts [hunk 20]
```diff
@@ -0,0 +1,129 @@
...
+            nextKey: null,
+            values
+          });
+        }
+      })
+      .on("error", reject);
+  });
+}
+
+export async function getStorage(
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts:111]: jsdoc would be nice

File: src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts [hunk 21]
```diff
@@ -0,0 +1,129 @@
...
+        };
+      })
+    );
+  }
+  await Promise.all(promises);
+
+  return storage;
+}
+
+export async function dumpTrieStorageDetails(
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts:150]: jsdoc would be nice

File: src/chains/ethereum/ethereum/src/blockchain.ts [hunk 22]
```diff
@@ -1164,17 +1162,11 @@ export default class Blockchain extends Emittery<BlockchainTypedEvents> {
...
-    keys?: Buffer[],
-    contractAddress?: Buffer
-  ): Promise<TraceTransactionResult> => {
-    let currentDepth = -1;
-    const storageStack: TraceStorageMap[] = [];
-
+    block: RuntimeBlock & { transactions: VmTransaction[] }
+  ): Promise<VM & { stateManager: GanacheStateManager }> => {
     const blocks = this.blocks;
     // ethereumjs vm doesn't use the callback style anymore
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/blockchain.ts:1214]: seems like an unnecessary comment at this point, can we remove? (I know you didn't add it in this PR, but since we're here)
```suggestion
```

File: src/chains/ethereum/ethereum/src/blockchain.ts [hunk 23]
```diff
@@ -1187,21 +1179,60 @@ export default class Blockchain extends Emittery<BlockchainTypedEvents> {
     const common = this.fallback
       ? this.fallback.getCommonForBlockNumber(
           this.common,
-          BigInt(newBlock.header.number.toString())
+          BigInt(block.header.number.toString())
         )
       : this.common;
 
     const vm = await VM.create({
-      state: trie,
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/blockchain.ts]: For future reviewers: the `state` field is ignored if `stateManager` is passed, so this wasn't ever necessary

File: src/chains/ethereum/ethereum/src/blockchain.ts [hunk 24]
```diff
@@ -1540,102 +1500,53 @@ export default class Blockchain extends Emittery<BlockchainTypedEvents> {
...
-      parentBlock,
-      transactionHashBuffer
-    );
-    // get storage data given a set of keys
-    const options = {
-      disableMemory: true,
-      disableStack: true,
-      disableStorage: false
-    };
+      // ethereumjs-vm has a dumpStorage(account) method, but we need to honor
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/blockchain.ts]: I was a little confused about the placement of this comment. Should it be over `dumpTrieStorageDetails`?

File: src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts [hunk 25]
```diff
@@ -134,141 +147,108 @@ describe("api", () => {
 
       it("should return account doesn't exist error when debugging a deployment transaction", async () => {
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts:148]:
```suggestion
      it("should return "account doesn't exist" error when debugging a deployment transaction", async () => {
```
pls

File: src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts [hunk 26]
```diff
@@ -134,141 +147,108 @@ describe("api", () => {
...
 
         assert.deepStrictEqual(result.storage, storage);
         assert.strictEqual(result.nextKey, null);
       });
 
-      it("should return correct storage given different transaction indexes", async () => {
+      it("should return correct storage given different storage slot changes at different transaction indexes in same block", async () => {
         /* 
           Strategy for this test:
             1. Create snapshot
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts:240]: What is the purpose of the snapshot/revert in this test?

**Review by MicaiahReid — DISMISSED** [review]

File: src/chains/ethereum/ethereum/src/api.ts [hunk 27]
```diff
@@ -2981,14 +2982,22 @@ export default class EthereumApi implements Api {
    * console.log(storage);
    * ```
    */
+  @assertArgLength(5)
```
Comment (jeffsmale90) [inline src/chains/ethereum/ethereum/src/api.ts:3190]: I can't comment on the correct line, because you didn't change it. The example here doesn't work, and I think it's because the 4 byte signature for the `value()` accessor should be `0x3fa4f245` not `0x55241077`.

At least that's what I get when I compile the contract, and it works if I change :
```javascript
const data = "0x552410770000000000000000000000000000000000000000000000000000000000000019";`
```
to
```javascript
const data = "0x3fa4f2450000000000000000000000000000000000000000000000000000000000000019";`
```

File: src/chains/ethereum/ethereum/src/api.ts (hunk 3 above)
Comment (jeffsmale90) [reply src/chains/ethereum/ethereum/src/api.ts:3201]: https://github.com/trufflesuite/ganache/issues/3488

File: src/chains/ethereum/ethereum/src/blockchain.ts [hunk 28]
```diff
@@ -1187,21 +1179,60 @@ export default class Blockchain extends Emittery<BlockchainTypedEvents> {
     const common = this.fallback
```
Comment (jeffsmale90) [inline src/chains/ethereum/ethereum/src/blockchain.ts:1224]: Another "you didn't do it, but..."

```
const block = await blocks.get(number.toBuffer()).catch(_ => null);
```

The `catch` here might be extraneous, as we catch "NOTFOUND" exceptions in `manager.ts` https://github.com/trufflesuite/ganache/blob/3a74e07ea9a90ec7d6749cfad5703d679ba0dac1/src/chains/ethereum/ethereum/src/data-managers/manager.ts#L30

Do with that thought what you will.

File: src/chains/ethereum/ethereum/src/blockchain.ts [hunk 29]
```diff
@@ -1164,17 +1162,11 @@ export default class Blockchain extends Emittery<BlockchainTypedEvents> {
     }
   }
 
-  #traceTransaction = async (
-    transaction: VmTransaction,
+  #fastForwardVM = async (
```
Comment (jeffsmale90) [inline src/chains/ethereum/ethereum/src/blockchain.ts]: This _creates_ a fastForward vm right? would it be worthwhile naming it `createFastForwardVm`? A comment explaining what it does might be in order, as I took a while to untangle this and `prepareNextBlock` below.

My understand is that this will run _up to but not including_ the provided transaction index - would be good to indicate that (especially because `prepareNextBlock` _includes_ the provided `transactionIndex`.

File: src/chains/ethereum/ethereum/src/blockchain.ts (hunk 7 above)
Comment (jeffsmale90) [reply src/chains/ethereum/ethereum/src/blockchain.ts:1455]: I made a similar comment regarding `fastForwardVM` - a comment explaining what this function does (including the inclusiveness of transactionIndex) might be helpful.

File: src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts [hunk 30]
```diff
@@ -0,0 +1,129 @@
...
+
+type TrieData = { key: Buffer; value: Buffer };
+type HashedKeysWithValues = {
+  length: number;
+  values: Buffer[];
+  keys: Buffer[];
+  nextKey: Data | null;
+};
+
+const compare = (a: Buffer, b: Buffer) => a.compare(b) < 0;
```
Comment (jeffsmale90) [inline src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts:29]: I guess this is mostly just moving stuff around, but it seems unnecessary to provide a comparator, when we don't provide anything but the default buffer comparator. I'd rather just have this function hard coded within the `findInsertPosition` function.

File: src/chains/ethereum/ethereum/tests/contracts/DebugStorage.sol [hunk 31]
```diff
@@ -5,20 +5,27 @@ contract DebugStorage {
   uint public value;
   uint public valueTwo;
   string public valueThree;
+  uint public value4;
```
Comment (jeffsmale90) [inline src/chains/ethereum/ethereum/tests/contracts/DebugStorage.sol:8]: is there a reason that this is `value4` and not `valueFour` like the others?

**Review by jeffsmale90 — CHANGES_REQUESTED** [review]

File: src/chains/ethereum/ethereum/src/api.ts (hunk 3 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/api.ts:3201]: @MicaiahReid The link was in the `Error`.

File: src/chains/ethereum/ethereum/src/api.ts (hunk 27 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/api.ts:3190]: Great catch! `55241077` is `setValue`  :facepalm:

Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/api.ts:3190]: fixed in https://github.com/trufflesuite/ganache/pull/3470/commits/6197023e85faf135a13adcd61668a00965f83ca2

File: src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts (hunk 30 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts:29]: The only reason I'll push back on this a tiny bit is because `findInsertPosition` was ported from C++, and that implementation takes a comparator, and it can compare _anything_, not just Buffers. If we hardcode the comparator we'll have to update `findInsertPosition` to be monomorphic (Buffers only).

File: src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts (hunk 21 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts:150]: added in https://github.com/trufflesuite/ganache/pull/3470/commits/950e7b94261acdc56d4a6aa4e22c928b1e3cf836

File: src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts (hunk 20 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts:111]: added in https://github.com/trufflesuite/ganache/pull/3470/commits/950e7b94261acdc56d4a6aa4e22c928b1e3cf836

File: src/chains/ethereum/ethereum/src/state-manager.ts (hunk 11 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/state-manager.ts]: I don't think we should update precompiles.ts, since it is using those just for the types.

_Theoretically_ this could be useful if we obtained a `stateManager` instance from something like `vm.stateManager`, and that instance's type returned only `StateManager` (despite it being a full `GanacheStateManager` with whatever _extra_ properties that may include). Since precompiles doesn't _need_ the extras from `GanacheStateManager`, using the narrower type is usually preferred.

File: src/chains/ethereum/ethereum/tests/contracts/DebugStorage.sol (hunk 31 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/tests/contracts/DebugStorage.sol:8]: no reason. fixed in https://github.com/trufflesuite/ganache/pull/3470/commits/d2da0f52f5562526235dc7b005da76dfb7dd79e7

File: src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts (hunk 25 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts:148]: This suggestion would break things because it isn't quoted correctly; also, the error message isn't _exactly_ `"account doesn't exist"`, so quoting it is a bit odd.

File: src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts (hunk 30 above)
Comment (jeffsmale90) [reply src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts:29]: Defs not worthwhile holding up this PR, but it might be worthwhile considering that especially if performance is important for this function. I _guess_ the comparator can be invoked a lot?

**Review by jeffsmale90 — APPROVED** [review]

File: src/chains/ethereum/ethereum/src/api.ts (hunk 3 above)
Comment (MicaiahReid) [reply src/chains/ethereum/ethereum/src/api.ts:3201]: You guys are so dang smart.

File: src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts (hunk 25 above)
Comment (MicaiahReid) [reply src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts:148]: Ahh, you're so right. Reading that `it` statement took me about 5 attempts to understand it, but based off of my other review suggestions from that day, I think I was a little slow when I reviewed this :sweat_smile:

File: src/chains/ethereum/utils/src/types/debug-storage.ts [hunk 32]
```diff
@@ -1,18 +1,14 @@
...
-  {
-    key: Data;
-    value: Data;
-  }
->;
+type StorageRecord = {
+  key: Data;
+  value: Data;
+};
+export type StorageRecords = Record<string, StorageRecord>;
```
Comment (tenthirtyone) [inline src/chains/ethereum/utils/src/types/debug-storage.ts:7]: I was like "Wouldn't `StorageRecord**s**` be a collection for `StorageRecord` not `Record`" and then I was like "Where is Record coming from"? 

And that's when learning occurred. Their utility naming does force a double take from the uninitiated (me).

File: src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts [hunk 33]
```diff
@@ -0,0 +1,152 @@
...
+    const values: Buffer[] = [];
+
+    trie
+      .createReadStream()
+      .on("data", function onData({ key, value }: TrieData) {
+        // ignore anything that comes before our starting point
+        if (startKey.compare(key) > 0) return;
+
+        // insert the key exactly where it needs to go in the array
+        const position = findInsertPosition(keys, key, compare);
```
Comment (tenthirtyone) [inline src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts:63]: totally unnecessary thought on optimizing.

If we hold `highestKey` in memory and `highestKey` === the highest key value in the `keys` array 
could we compare `keys.length === maxKeys && key > highestKey` return? This would guarantee we only find the insert position for keys that could be in the array once it is full by automatically dropping keys that are too high


I think that would guarantee you always have the keys you want but it would only insertion sort `maxKeys` instead of keys greater than `startKey` 

This _might_ eliminate the need for the `length > maxKeys` in the `end`

**Review by tenthirtyone — COMMENTED** [review]
Just comments no changes requested

File: src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts (hunk 33 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts:63]: I originally thought you were on to something (and you still might be) and started implementing this, but I realized ( I think) that if `key` ends up being less than `highestKey`, we still will need to insert into the array, which will make the array too long; so we still need to trim it down to size somehow. So we don't eliminate the `length > maxKeys` check.

Additionally, we _need_ to collect one more key than `maxKeys`, in order to find and return the `nextKey` value. So while there may be something to your optimization idea, implementing it started getting a bit complex so I've bailed and am here writing this comment now. Let me know if you want to pair on this and make we can make the optimization make more sense!

File: src/chains/ethereum/ethereum/src/blockchain.ts (hunk 24 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/blockchain.ts]: I've moved it!

File: src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts (hunk 26 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts:240]: These tests share a `provider`. It's just the way it was already, so I didn't update it to use `beforeEach`.

File: src/chains/ethereum/ethereum/src/blockchain.ts (hunk 28 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/blockchain.ts:1224]: made an issue for it here: https://github.com/trufflesuite/ganache/issues/3841

File: src/chains/ethereum/ethereum/src/blockchain.ts (hunk 29 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/blockchain.ts]: done!

File: src/chains/ethereum/ethereum/src/blockchain.ts (hunk 7 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/blockchain.ts:1455]: done!

File: src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts (hunk 19 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/tests/api/debug/debug_storageRangeAt.test.ts:25]: made an issue for it here: https://github.com/trufflesuite/ganache/issues/3842

File: src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts (hunk 33 above)
Comment (tenthirtyone) [reply src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts:63]: Much appreciation to the time put in. 

I [made a branch](https://github.com/trufflesuite/ganache/blob/storageRangePrune/src/packages/utils/tests/utils.test.ts) with unit tests to show existing vs suggested. 

The TLDR is [one line](https://github.com/trufflesuite/ganache/blob/storageRangePrune/src/packages/utils/tests/utils.test.ts#L101).

I believe the existing code is the 'corner office' (best) solution.

It _is_ possible for the suggested custom solution to work without the `if (position > maxKeys) return;` however performance suffers greatly. 

The only time I saw the linked suggestion bench faster is when there were >1000 keys but I believe this is only due to the test conditions -> I simplified it to test against integers. The custom should prune operations when `position` equals `maxLength-1`. E.g. a key collision for the final item in the results array. 

I don't believe that is possible in production. Sharing code/thoughts for code/thoughts sake.

Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts:63]: So would you like to chase this optimization further or is the code good as is?

Comment (tenthirtyone) [reply src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts:63]: > I believe the existing code is the 'corner office' (best) solution.

Good to go

File: src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts (hunk 20 above)
Comment (MicaiahReid) [reply src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts:111]: I'm not seeing it as part of this branch. Is there some weird git stuff going on?

File: src/chains/ethereum/ethereum/src/forking/state-manager.ts [hunk 34]
```diff
@@ -1,13 +1,13 @@
...
+import { decode } from "@ganache/rlp";
 import { ForkCache } from "./cache";
 import { ForkTrie } from "./trie";
 import { GanacheStateManager } from "../state-manager";
 
 /**
  * Options for constructing a [[GanacheStateManager]].
  */
-export interface GanacheStateManagerOpts {
+export interface ForkStateManagerOpts {
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/forking/state-manager.ts:10]: I changed this name - it doesn't really have anything to do with the merge. I just thought that it was weird that we were calling it `GanacheStateManagerOpts` when it specifies a trie of type `ForkTrie`.

File: src/chains/ethereum/ethereum/src/forking/state-manager.ts [hunk 35]
```diff
@@ -42,7 +43,7 @@ export class ForkStateManager extends GanacheStateManager {
    * at the last fully committed point, i.e. as if all current
    * checkpoints were reverted.
    */
-  copy(): GanacheStateManager {
+  copy(): ForkStateManager {
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/forking/state-manager.ts:46]: Another one that I changed that's unrelated to the merge. But figured the types should line up and I was here so...

File: src/chains/ethereum/ethereum/src/blockchain.ts [hunk 36]
```diff
@@ -734,7 +733,7 @@ export default class Blockchain extends Emittery<BlockchainTypedEvents> {
       const { miner: minerOptions } = this.#options;
 
       // commit accounts, but for forking.
-      const stateManager = <GanacheStateManager>this.vm.stateManager;
+      const stateManager = <DefaultStateManager>this.vm.stateManager;
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/blockchain.ts]: Most of the time I'm changing from `DefaultStateManager` to `GanacheStateManager`. Here I'm doing the reverse. This is in the `initializeGenesisBlock` function, and as far as I can tell there's no reason for this to be a `GanacheStateManager`.

File: src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts (hunk 20 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/helpers/storage-range-at.ts:111]: Fixed in https://github.com/trufflesuite/ganache/pull/3470/commits/b36eb4b3f0865351ba4c981dc7604c1c37167f54

**Review by MicaiahReid — APPROVED** [review]

**Review by jeffsmale90 — APPROVED** [review]
