### PR TITLE
fix: enforce eip-2 imposed limits and secp256k1 upper bound for private keys

### LINKED ISSUE #2586: Transaction from unlocked account fails with error: "The nonce generation function failed, or the private key was invalid":
Hi, I'm unlocking this address: `0xffffFFFfFFffffffffffffffFfFFFfffFFFfFFfE` on a mumbai fork to try to emulate polygon system account.
When I send the following transaction I get in the ganache v7.0.0 container log I get the error `"The nonce generation function failed, or the private key was invalid"`:
```
mumbai_1 | > eth_sendTransaction: [ 
mumbai_1 | > { 
mumbai_1 | > "gas": "0xcd3f", 
mumbai_1 | > "from": "0xfffffffffffffffffffffffffffffffffffffffe", 
mumbai_1 | > "to": "0x0000000000000000000000000000000000001001", 
mumbai_1 | > "data": "...."
```
Even a transfer tx fails with the same error: 
```
mumbai_1   |    >  eth_sendTransaction: [
mumbai_1   |    >   {
mumbai_1   |    >     "from": "0xfffffffffffffffffffffffffffffffffffffffe",
mumbai_1   |    >     "to": "0x5f890c9522dce5670d741d4277bfcc2d9ca8af02",
mumbai_1   |    >     "value": "0x12",
mumbai_1   |    >     "gasPrice": "0x77359400"
mumbai_1   |    >   }
```
Is seems this error happens when trying to ecsign with the fake private key.

Any idea ?

### LINKED ISSUE #2600: All transaction signatures whose s-value is greater than secp256k1n/2 are now considered invalid, but ganache accepts them
According to EIP-2 "All transaction signatures whose s-value is greater than secp256k1n/2 are now considered invalid."
the signature generated by hardware wallet has s component greater than secp256k1n/2 .

Ganache currently permits this greater "s" value.

### PR DESCRIPTION
**Pull request by davidmurdoch**
Sending transactions from an impersonated account with a "large" account number, like `fffffffffffffffffffffffffffffffffffffffe`, would result in the error "The nonce generation function failed, or the private key was invalid" due to the way we fake transaction signing in ganache. Previously we would take the account number plus the first 12 bytes of the account number, `fffffffffffffffffffffffffffffffffffffffe` + `ffffffffffffffffffffffff`, and would use that as a fake private key. This results in an invalid key, as secp256k1, the elliptic curve used in Ethereum cryptography, has an effective maximum private key value of `0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140n` (AKA `secp256k1_n - 1`, or the total number of non-trivial points on the curve). This fixes #2586.

While implementing this fix it was discovered that we were not rejecting transactions with too-high s-values; i.e., s-values that are greater than `(secp256k1_n - 1) / 2`. This restriction was added way back in Ethereum's first hardfork, homestead, as part of [EIP-2](https://eips.ethereum.org/EIPS/eip-2) in order to remove the possibility of "malleable" transactions. While somewhat unrelated to the core reason for this fix, it has been added as part of this PR. This fixes #2600.

### CODE REVIEW

File: src/chains/ethereum/ethereum/src/wallet.ts [hunk 1]
```diff
@@ -636,7 +638,45 @@ export default class Wallet {
...
+      // will. There are obviously many chances for a false positive, but the
+      // next condition in the `while` loop will catch those.
+      if (first12.compare(TWELVE_255s) === 0) {
+        while (
+          BigInt(`0x${fakePrivateKey.toString("hex")}`) >=
+          SECP256K1_MAX_PRIVATE_KEY
+        ) {
+          // keccak returns a 32 byte hash of the input data, which is the exact
+          // length we need for a private key.
+          // note: if keccak can return it's own input as it's output, then this
```
Comment (davidmurdoch) [inline src/chains/ethereum/ethereum/src/wallet.ts]:
```suggestion
          // note: if keccak can return its own input as its output, then this
```

File: src/chains/ethereum/ethereum/src/wallet.ts [hunk 2]
```diff
@@ -23,6 +23,8 @@ import { writeFileSync } from "fs";
 import { EthereumInternalOptions } from "@ganache/ethereum-options";
 import { Address } from "@ganache/ethereum-address";
 
+const TWELVE_255s = Buffer.allocUnsafe(12).fill(255);
```
Comment (MicaiahReid) [inline src/chains/ethereum/ethereum/src/wallet.ts:26]: This is a great variable name. Bravo.

File: src/chains/ethereum/transaction/tests/index.test.ts [hunk 3]
```diff
@@ -169,6 +170,65 @@ describe("@ganache/ethereum-transaction", async () => {
...
+          const genesis = Common.forCustomChain(
+            "mainnet",
+            {
+              name: "ganache",
+              chainId: 1,
+              comment: "Local test network",
+              bootstrapNodes: []
+            },
+            // EIP-2 was in homestead, the first hardfork, so we need to create
+            // a common at the genesis (eke chainstart) so we can test at a fork
```
Comment (MicaiahReid) [inline src/chains/ethereum/transaction/tests/index.test.ts]:
```suggestion
            // a common at the genesis (aka chainstart) so we can test at a fork
```
Unless `eke` means something I'm not aware of?

File: src/chains/ethereum/transaction/tests/index.test.ts [hunk 4]
```diff
@@ -169,6 +170,65 @@ describe("@ganache/ethereum-transaction", async () => {
         const txFromRpc = TransactionFactory.fromRpc(tempAccessListTx, common);
         assert.strictEqual(txFromRpc.type.toString(), "0x0");
       });
+
+      describe("EIP-2", () => {
```
Comment (MicaiahReid) [inline src/chains/ethereum/transaction/tests/index.test.ts:174]: Cool test!

**Review by MicaiahReid — CHANGES_REQUESTED** [review]

**Comment by MicaiahReid** [comment]
Reviewed! This also needs a description that is release ready.

File: src/chains/ethereum/ethereum/src/wallet.ts (hunk 2 above)
Comment (davidmurdoch) [reply src/chains/ethereum/ethereum/src/wallet.ts:26]: Thanks for noticing. This line took me two weeks to get right!

**Review by MicaiahReid — APPROVED** [review]
